[project]
name = "benchmarking-qubo-approaches"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "amplify>=1.3.1",
    "dotenv>=0.9.9",
    "numpy>=2.3.1",
    "pyqubo>=1.5.0",
    "scikit-learn>=1.7.1",
]
